// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFV0YdERxcwG42xioD2UGJ4CujZ54L4Q',
    appId: '1:1053688684931:web:5febc4f3815a7646cd16b6',
    messagingSenderId: '1053688684931',
    projectId: 'kseb-f73cf',
    authDomain: 'kseb-f73cf.firebaseapp.com',
    storageBucket: 'kseb-f73cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasLnNKkfoT7afiLCz0cclQcfv0g9JCis',
    appId: '1:1053688684931:android:941a40307e525223cd16b6',
    messagingSenderId: '1053688684931',
    projectId: 'kseb-f73cf',
    storageBucket: 'kseb-f73cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNZawdxQ9oUd1mEOqRGuADkb2VbMGsGs',
    appId: '1:1053688684931:ios:3107369d147e2000cd16b6',
    messagingSenderId: '1053688684931',
    projectId: 'kseb-f73cf',
    storageBucket: 'kseb-f73cf.firebasestorage.app',
    iosBundleId: 'com.example.kseb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNZawdxQ9oUd1mEOqRGuADkb2VbMGsGs',
    appId: '1:1053688684931:ios:3107369d147e2000cd16b6',
    messagingSenderId: '1053688684931',
    projectId: 'kseb-f73cf',
    storageBucket: 'kseb-f73cf.firebasestorage.app',
    iosBundleId: 'com.example.kseb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFV0YdERxcwG42xioD2UGJ4CujZ54L4Q',
    appId: '1:1053688684931:web:295dddbe5b26aa0fcd16b6',
    messagingSenderId: '1053688684931',
    projectId: 'kseb-f73cf',
    authDomain: 'kseb-f73cf.firebaseapp.com',
    storageBucket: 'kseb-f73cf.firebasestorage.app',
  );
}
