import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

// Design system tokens
import 'utils/app_colors.dart';
import 'utils/app_typography.dart';
import 'utils/app_spacing.dart';
import 'utils/page_transitions.dart';

// Import screen files
import 'screens/auth_gate.dart';

// Make sure you have this file generated by the FlutterFire CLI
import 'firebase_options.dart';

/// Build the app-wide ThemeData from design tokens.
///
/// Every ColorScheme role, component theme, and text theme slot references
/// a token constant — no hex literals or magic numbers.
ThemeData createAppTheme() {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.primary,
      onPrimary: AppColors.textOnPrimary,
      primaryContainer: AppColors.primaryWithLowOpacity,
      onPrimaryContainer: AppColors.primaryDark,
      secondary: AppColors.secondary,
      onSecondary: AppColors.textOnPrimary,
      secondaryContainer: AppColors.secondary.withValues(alpha: 0.08),
      onSecondaryContainer: AppColors.secondary,
      tertiary: AppColors.accent,
      onTertiary: AppColors.textOnPrimary,
      error: AppColors.error,
      onError: AppColors.textOnPrimary,
      surface: AppColors.surface,
      onSurface: AppColors.textPrimary,
      surfaceContainerHighest: AppColors.grey200,
      outline: AppColors.grey300,
      outlineVariant: AppColors.grey200,
      shadow: AppColors.cardShadow,
    ),
    textTheme: _buildTextTheme(),
    appBarTheme: AppBarTheme(
      backgroundColor: AppColors.surface,
      foregroundColor: AppColors.textPrimary,
      elevation: 0.5,
      surfaceTintColor: Colors.transparent,
      shadowColor: AppColors.shadowLight,
      centerTitle: true,
      titleTextStyle: AppTypography.headingStyle,
    ),
    cardTheme: CardThemeData(
      color: AppColors.surface,
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
      ),
      margin: EdgeInsets.zero,
    ),
    inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
        borderSide: BorderSide(color: AppColors.primary, width: 1.5),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
        borderSide: BorderSide(color: AppColors.error),
      ),
      labelStyle: AppTypography.captionStyle,
      hintStyle: TextStyle(color: AppColors.textPlaceholder),
      contentPadding: EdgeInsets.symmetric(
        horizontal: AppSpacing.base,
        vertical: AppSpacing.md,
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: AppColors.primary,
        foregroundColor: AppColors.textOnPrimary,
        minimumSize: const Size(0, 56),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
        ),
        textStyle: AppTypography.bodyMediumStyle,
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: AppColors.primary,
        textStyle: AppTypography.bodyStyle,
      ),
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: AppColors.primary,
      foregroundColor: AppColors.textOnPrimary,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
      ),
    ),
    pageTransitionsTheme: const PageTransitionsTheme(
      builders: {
        TargetPlatform.android: AppPageTransition(),
        TargetPlatform.iOS: AppPageTransition(),
        TargetPlatform.windows: AppPageTransition(),
        TargetPlatform.macOS: AppPageTransition(),
        TargetPlatform.linux: AppPageTransition(),
      },
    ),
  );
}

/// Build text theme.
/// Note: google_fonts disabled due to constant evaluation error on Windows builds.
TextTheme _buildTextTheme() {
  return ThemeData.light().textTheme.copyWith(
    displayLarge: AppTypography.displayLargeStyle,
    displayMedium: AppTypography.displayStyle,
    titleLarge: AppTypography.titleStyle,
    titleMedium: AppTypography.headingStyle,
    titleSmall: AppTypography.subheadingStyle,
    bodyLarge: AppTypography.bodyMediumStyle,
    bodyMedium: AppTypography.bodyStyle,
    bodySmall: AppTypography.captionStyle,
  );
}

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Form Filing App',
      theme: createAppTheme(),
      debugShowCheckedModeBanner: false,
      // AuthGate handles reactive auth state and navigates to the correct screen
      home: const AuthGate(),
    );
  }
}
