import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';

// Design system tokens
import 'utils/app_colors.dart';
import 'utils/app_typography.dart';
import 'utils/app_spacing.dart';
import 'components/common/app_loading.dart';

// Import screen files
import 'screens/login_screen.dart';
import 'screens/worker_home_screen.dart';

// Make sure you have this file generated by the FlutterFire CLI
import 'firebase_options.dart';

/// Build the app-wide ThemeData from design tokens.
///
/// Every ColorScheme role, component theme, and text theme slot references
/// a token constant — no hex literals or magic numbers.
ThemeData createAppTheme() {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.primary,
      onPrimary: AppColors.textOnPrimary,
      primaryContainer: AppColors.primaryWithLowOpacity,
      onPrimaryContainer: AppColors.primaryDark,
      secondary: AppColors.secondary,
      onSecondary: AppColors.textOnPrimary,
      secondaryContainer: AppColors.secondary.withValues(alpha: 0.08),
      onSecondaryContainer: AppColors.secondary,
      tertiary: AppColors.accent,
      onTertiary: AppColors.textOnPrimary,
      error: AppColors.error,
      onError: AppColors.textOnPrimary,
      surface: AppColors.surface,
      onSurface: AppColors.textPrimary,
      surfaceContainerHighest: AppColors.grey200,
      outline: AppColors.grey300,
      outlineVariant: AppColors.grey200,
      shadow: AppColors.cardShadow,
    ),
    textTheme: GoogleFonts.interTextTheme().copyWith(
      displayLarge: AppTypography.displayLargeStyle,
      displayMedium: AppTypography.displayStyle,
      titleLarge: AppTypography.titleStyle,
      titleMedium: AppTypography.headingStyle,
      titleSmall: AppTypography.subheadingStyle,
      bodyLarge: AppTypography.bodyMediumStyle,
      bodyMedium: AppTypography.bodyStyle,
      bodySmall: AppTypography.captionStyle,
    ),
    appBarTheme: AppBarTheme(
      backgroundColor: AppColors.surface,
      foregroundColor: AppColors.textPrimary,
      elevation: 0.5,
      surfaceTintColor: Colors.transparent,
      shadowColor: AppColors.shadowLight,
      centerTitle: true,
      titleTextStyle: AppTypography.headingStyle,
    ),
    cardTheme: CardTheme(
      color: AppColors.surface,
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
      ),
      margin: EdgeInsets.zero,
    ),
    inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
        borderSide: BorderSide(color: AppColors.primary, width: 1.5),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
        borderSide: BorderSide(color: AppColors.error),
      ),
      labelStyle: AppTypography.captionStyle,
      hintStyle: TextStyle(color: AppColors.textPlaceholder),
      contentPadding: EdgeInsets.symmetric(
        horizontal: AppSpacing.base,
        vertical: AppSpacing.md,
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: AppColors.primary,
        foregroundColor: AppColors.textOnPrimary,
        minimumSize: const Size(0, 56),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
        ),
        textStyle: AppTypography.bodyMediumStyle,
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: AppColors.primary,
        textStyle: AppTypography.bodyStyle,
      ),
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: AppColors.primary,
      foregroundColor: AppColors.textOnPrimary,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusDefault),
      ),
    ),
  );
}

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Form Filing App',
      theme: createAppTheme(),
      debugShowCheckedModeBanner: false,
      // StreamBuilder will listen to auth changes and show the correct screen
      home: SafeArea(
        child: StreamBuilder<User?>(
          stream: FirebaseAuth.instance.authStateChanges(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              // Show a loading indicator while checking auth state
              return const Scaffold(
                body: Center(child: AppLoading()),
              );
            }
            if (snapshot.hasData) {
              // If user is logged in, show worker home screen
              // TODO: Add logic to differentiate between worker, supervisor, admin
              return const WorkerHomeScreen();
            }
            // If user is not logged in, show login screen
            return const LoginScreen();
          },
        ),
      ),
    );
  }
}
